### ISSUE TITLE
stuck on Exception In Checker

### ISSUE THREAD

**Issue by bobo4545** [BornPaster/CapCrack#1]
I use the linux system, and it will get stuck almost at the place where Exception is executed.

![image](https://user-images.githubusercontent.com/49523109/222950901-644e3552-025f-4ce7-a30f-673e1339912f.png)
and again...
![image](https://user-images.githubusercontent.com/49523109/222951010-dfa821e2-9012-490e-989c-6038392d2678.png)

**Comment by BornPaster** [comment]
When it says “Expecting Value (etc)” it means it’s checking proxies to find a valid one. They don’t all work cuz it’s getting them off of a free proxy api. You’ll have to keep it running for a while to get a valid key
